In [4]:
import numpy as np
a = np.array ([[1,2,4],[5,8,7]])
print("Array created using passed list \n",a)

Array created using passed list 
 [[1 2 4]
 [5 8 7]]


In [5]:
b = np.zeros((3,4))
print("\n An array initialized with all zeros \n",b);


 An array initialized with all zeros 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
c = np.full((33),6)
print("\n array initialized with all b\n",c)


 array initialized with all b
 [6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [11]:
d = np.random.random((2,2))
print("\n A random array\n", d)


 A random array
 [[0.25941008 0.35681978]
 [0.0494427  0.2789946 ]]


In [14]:
e = np.arange(0,30,5)
print("\n A sequential array with step of 5\n",e)


 A sequential array with step of 5
 [ 0  5 10 15 20 25]


In [16]:
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
reshaped_arr =arr.reshape(4,3)
print(arr)
print(reshaped_arr)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [18]:
fl_arr = arr.flatten()
print(arr)
print(fl_arr)
print(arr.ndim)
print(arr.shape)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]
2
(3, 4)
